theme: jekyll-theme-minimal
title: Game of the Week Club
description: A podcast with four friends talking about a different game every week!
logo: gotw sfc logo 4 glossy.png
url: https://gameoftheweek.club
